CREATE TABLE A ( _id VARCHAR(24) ,PRIMARY KEY(_id), title VARCHAR(120) ,author VARCHAR(24) ,published_date DATETIME ,pages BIGINT ,language VARCHAR(24) ,publisher_id BIGINT  ) 
CREATE TABLE publisher ( publisher2_id BIGINT ,_id BIGINT ,PRIMARY KEY(_id), name VARCHAR(24) ,founded INT ,location VARCHAR(24)  ) 
CREATE TABLE publisher2 ( _id BIGINT ,PRIMARY KEY(_id), name VARCHAR(24) ,founded INT ,location VARCHAR(24)  ) 
CREATE TABLE B ( name VARCHAR(24) ,founded INT ,location VARCHAR(24) ,_id INT ,PRIMARY KEY(_id), title VARCHAR(120) ,author VARCHAR(24) ,published_date DATETIME ,pages INT ,language VARCHAR(24)  ) 
CREATE TABLE C ( name VARCHAR(24) ,founded INT ,location VARCHAR(24) ,_id INT ,PRIMARY KEY(_id), title VARCHAR(120) ,author VARCHAR(24) ,published_date DATETIME ,pages INT ,language VARCHAR(24) ,publisher_id VARCHAR(24)  ) 
CREATE TABLE POLA ( _id VARCHAR(24) ,PRIMARY KEY(_id), test INT  ) 
CREATE TABLE test ( _id VARCHAR(24) ,PRIMARY KEY(_id), aaa VARCHAR(24)  ) 
CREATE TABLE author ( value VARCHAR(24) ,C_id INT  ) 
CREATE TABLE books ( value INT ,B_id VARCHAR(24)  ) 
